---
title: "04-Markdowns-Templates"
output: html_document
---

```{r}
library('usethis')
```


```{r}
name_temp <-"01_Basics_of_R"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "This R markdown aims to provide a brief introduction of `R` language and the concepts of data.")

source_file <- here("data-raw", "01_basics_of_R.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"02_Exploratory_Data_Analysis"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "This R markdown aims to provide a brief introduction to Exploratory Data Analysis (EDA).")

source_file <- here("data-raw", "02_exploratory_data_analysis.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
usethis::use_rmarkdown_template(template_name = "03a_Census_Spatial_Files", 
                                template_description = "This R markdown aims to preparate the spatial dataset to perform the accessibility analysis.")
```

```{r}
name_temp <-"03_Preprocessing_Files"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "This R markdown aims to preparate the spatial dataset and matrix travel time to perform the accessibility analysis.")

source_file <- here("data-raw", "03_preprocessing_files.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"04DA_Accessibility_Measures"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "This R markdown allows to obtain accessibility measures for any Canadian study area at the Dissemination Area level.")

source_file <- here("data-raw", "04DA_accessibility_measures.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"05DA_Visualizing_Accessibility"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "Visualizing accessibility measures with maps - Dissemination Area level.")

source_file <- here("data-raw", "05DA_visualizing_accessibility_measures.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"04CT_Accessibility_Measures"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "This R markdown allows to obtain accessibility measures for cities located within Census Metropolitan Areas or Census Agglomerations at the Census Tract Level.")

source_file <- here("data-raw", "04CT_accessibility_measures.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"05CT_Visualizing_Accessibility"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "Visualizing accessibility measures with maps - Census Tract Level.")

source_file <- here("data-raw", "05CT_visualizing_accessibility_measures.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"06_Creating_Spatial_Filters"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "Creating synthetic instrumental variables from spatial filters.")

source_file <- here("data-raw", "06_creating_spatial_filter.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

```{r}
name_temp <-"07_Regression_Models"
usethis::use_rmarkdown_template(template_name = name_temp, 
                                template_description = "Linking job accessibility to employment outcomes.")

source_file <- here("data-raw", "07_regression_models.Rmd")
dest_file <- here("inst", "rmarkdown", "templates", tolower(name_temp), "skeleton", "skeleton.Rmd")

file.copy(source_file, dest_file, overwrite = TRUE)
```

